### ISSUE TITLE
CREATE EXTERNAL TABLE cannot run inside a transaction block

### ISSUE THREAD

**Issue by naveenarumugam** [hellonarrativ/spectrify#12]
* Spectrify version: 
* Python version:
* Operating System:

### Description
Trying to create the external table (3rd step of Spectrify)

### What I Did

```
>>> from spectrify.create import create_external_table
>>> from spectrify.utils.schema import get_table_schema2
>>> 
>>> sa_table = get_table_schema2(sa_engine, 'temp_table_01', meta) 
>>> create_external_table(sa_engine, 'spectrum', 'temp_table_01', sa_table, 's3://my_bucket/test_spectrify/parquet/redshift/my_schema/temp_table_01/')

*** CREATE TABLE SQL ***

create external table spectrum.temp_table_01 (
    return_item INTEGER,
    return_item_id INTEGER
)
stored as parquet
location 's3://my_bucket/test_spectrify/parquet/redshift/my_schema/temp_table_01/'


Continue? [y/N]: y
Creating table...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/spectrify/create.py", line 54, in create_external_table
    cursor.execute(formatted_query)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
    statement, parameters
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.InternalError) CREATE EXTERNAL TABLE cannot run inside a transaction block
 [SQL: "\ncreate external table spectrum.temp_table_01 (\n    return_item INTEGER,\n    return_item_id INTEGER\n)\nstored as parquet\nlocation 's3://my_bucket/test_spectrify/parquet/redshift/my_schema/temp_table_01/'\n"] (Background on this error at: http://sqlalche.me/e/2j85)
>>> 
```

**Comment by naveenarumugam** [comment]
@c-nichols  seems there's a dependent issue that you've created on https://github.com/sqlalchemy-redshift/sqlalchemy-redshift/issues/122

**Comment by naveenarumugam** [comment]
For now, I'm able to resolve the issue by  using this 
`sa_engine =  create_engine(url, connect_args={'sslmode': 'prefer'}, echo = False, isolation_level="AUTOCOMMIT")`
Somehow changing cursor.execute(formatted_query) to `cursor.execute(formatted_query)..execution_options(isolation_level="AUTOCOMMIT")` did not work.

**Comment by c-nichols** [comment]
Hi Naveen,

Yes, `CREATE EXTERNAL TABLE` is not supported from within a transaction.  See the documentation https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_EXTERNAL_TABLE.html

I believe that stock Spectrify does not start a transaction -- are you issuing a `BEGIN` statement or a `START TRANSACTION` statement?

**Comment by naveenarumugam** [comment]
Hi Nichols

I am not using BEGIN/START transaction; for now just setting the isolation level at the engine level, (but, on  a separate engine, that gets closed once done).

**Comment by c-nichols** [comment]
Yes I think that's what you will have to do.  I'm closing as this is a fundamental limitation of Redshift/Spectrum and I'm not sure how to improve improve Spectrify with regard to this issue.  Please reopen if you have ideas (or better yet, submit a PR ;)

**Comment by c-nichols** [comment]
@naveenarumugam  Of course as soon as I closed this, I figured out how to improve Spectrify :)

Check out my latest PR -- I am setting the correct isolation level in the function `create_external_table`.  Isolation level on the engine that is passed in can be anything.

**Comment by naveenarumugam** [comment]
Cool, Thanks @c-nichols

**Comment by jimomiaomiao** [comment]
can you show the complete code @naveenarumugam  thanks
