### ISSUE TITLE
ValueError: Type <class 'sqlalchemy.sql.sqltypes.NUMERIC'> not currently supported by Spectrify. 

### ISSUE THREAD

**Issue by naveenarumugam** [hellonarrativ/spectrify#14]
* Spectrify version: 0.4.0
* Python version: 2.7
* Operating System: Mac

### Description

  File "/usr/lib/python2.7/site-packages/spectrify/utils/schema.py", line 54, in get_table_schema2
    col.type.__class__
ValueError: Type <class 'sqlalchemy.sql.sqltypes.NUMERIC'> not currently supported by Spectrify. Open an issue?

### What I Did
Trying to  to csv to parquet 
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by naveenarumugam** [comment]
@c-nichols  
how about adding these mappings?  will the precisions taken care as per each row value or at the column level?  trying to understand if there's a reason you did not include it.

- NUMERIC: pa.decimal128,
- DECIMAL: pa.decimal128,

**Comment by andrewgross** [comment]
Precision should be per column, but is required when initializing the type.  Not sure if sqlalchemy gives access to those properties or if you need to ask Redshift directly.

**Comment by naveenarumugam** [comment]
@andrewgross cool, thanks. my bad, I was about to ask whether the object wrapping needs to be handled at row-level; but, nvm, got it.  Right now, the problem is afaik, the incoming column value needs to be created as decimal.Decimal object which in turn is used by pyarrow.decimal128, as decimal128 takes only Double values and no direct string input (such as "12.34") can be passed.

sqlalchemy gives table meta in wrapped Table object. Similar to querying directly. 

`sa_engine =  create_engine(url, connect_args={'sslmode': 'prefer'}, echo = False)   #True is NOISY
sa_meta     = sa.MetaData(sa_engine,'schema_name')
sa_table    = sa.Table('table_name', sa_meta, autoload=True, autoload_with=sa_engine)
for col in sa_table.columns:
      print col.name, col.type, col.type.__class__

**Comment by c-nichols** [comment]
I'm struggling with something on the pyarrow side.  The Parquet specification allows you to write DECIMALS with low levels of precision into 32- or 64-bit physical representations -- but the pyarrow API seems to only expose `pa.decimal128`.  It would be a bummer to expand these out to 128 bits if it's not necessary...

I'll start by taking your suggestion @naveenarumugam and just live with the inefficiency :) I'll integratethis over the next few days.

**Comment by c-nichols** [comment]
Unfortunately, Spectrum aborts the query with an error if the Parquet column is unnecessarily wide.  In other words, a `DECIMAL(4, 2)` column must be 32-bits wide; a `DECIMAL(18, 7)` column must be 64-bits wide.

Asking for some help on the arrow mailing list, as I haven't had much luck finding examples/relevant docs.

**Comment by cpcloud** [comment]
@c-nichols Is the issue that the values aren't represented using an integer physical type (they are currently using a fixed length byte array physical type), and not really that they are unnecessarily wide? Since parquet-cpp shrinks decimal values, the size should be exactly what's required for the specified scale and precision.

**Comment by cpcloud** [comment]
@c-nichols Can you show the error message you get?

**Comment by c-nichols** [comment]
Hi @cpcloud, appreciate you taking a look.  I get the feeling I'm doing something silly but can't sort it out based on the docs.

I populated a vanilla redshift table as follows --
```
CREATE TABLE spectrify_integration_test (
  created datetime not null,
  descrip varchar(200),
  long_descrip text,
  shorty smallint,
  medium integer,
  biggie bigint,
  smalldec DECIMAL(4,2),
  meddec DECIMAL(18, 7),
  hugedec DECIMAL(38, 24)
);

insert into spectrify_integration_test values
('2017-08-03', 'short text', 'loooooong text', 2, 22, 9223372036854775806, 12.34, 98765432198.7654321, 12345678912345.123456789123456789123456);
```

Then used Spectrify to create an external table and archive to Parquet.  Generated parquet file can be found here: https://s3.amazonaws.com/narrativ-public/spectrum/0003_part_00.parq

Output of Spectrum commands --
```
bamxstats=# select * from svv_external_columns where tablename = 'spectrify_integration_test';
 schemaname |         tablename          |  columnname  | external_type  | columnnum | part_key 
------------+----------------------------+--------------+----------------+-----------+----------
 spectrum   | spectrify_integration_test | created      | timestamp      |         1 |        0
 spectrum   | spectrify_integration_test | descrip      | varchar(200)   |         2 |        0
 spectrum   | spectrify_integration_test | long_descrip | varchar(256)   |         3 |        0
 spectrum   | spectrify_integration_test | shorty       | smallint       |         4 |        0
 spectrum   | spectrify_integration_test | medium       | int            |         5 |        0
 spectrum   | spectrify_integration_test | biggie       | bigint         |         6 |        0
 spectrum   | spectrify_integration_test | smalldec     | decimal(4,2)   |         7 |        0
 spectrum   | spectrify_integration_test | meddec       | decimal(18,7)  |         8 |        0
 spectrum   | spectrify_integration_test | hugedec      | decimal(38,24) |         9 |        0
(9 rows)

Time: 137.684 ms
bamxstats=# \x on
Expanded display is on.
bamxstats=# select * from svv_external_tables where tablename = 'spectrify_integration_test';
-[ RECORD 1 ]-----+---------------------------------------------------------------
schemaname        | spectrum
tablename         | spectrify_integration_test
location          | s3://bamx-stats-test/spectrify_integration_test/spectrum
input_format      | org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
output_format     | org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
serialization_lib | org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
serde_parameters  | {"serialization.format":"1"}
compressed        | 0
parameters        | {"EXTERNAL":"TRUE","transient_lastDdlTime":"1524198293"}

Time: 147.930 ms
bamxstats=# select * from spectrum.spectrify_integration_test;
ERROR:  S3 Query Exception (Fetch)
DETAIL:  
  -----------------------------------------------
  error:  S3 Query Exception (Fetch)
  code:      15001
  context:   Task failed due to an internal error. File 'https://s3.amazonaws.com/bamx-stats-test/spectrify_integration_test/spectrum/0003_part_00.parq  column 'smalldec' has an invalid type length. Expecting: 2 len in file: 16

  query:     16105240
  location:  dory_util.cpp:716
  process:   query0_97_16105240 [pid=7475]
  -----------------------------------------------

Time: 1692.377 ms
bamxstats=# 
```

**Comment by cpcloud** [comment]
@c-nichols It looks like the parquet file you've linked to is actually writing decimal values as `DECIMAL(38,24)` for every decimal field, including `smalldec`:

```
message schema {
  optional int96 created;
  optional binary descrip (UTF8);
  optional binary long_descrip (UTF8);
  optional int32 shorty (INT_16);
  optional int32 medium;
  optional int64 biggie;
  optional fixed_len_byte_array(16) smalldec (DECIMAL(38,24));
  optional fixed_len_byte_array(16) meddec (DECIMAL(38,24));
  optional fixed_len_byte_array(16) hugedec (DECIMAL(38,24));
}
```

I can confirm that with pyarrow 0.9.0 we're writing the correct number of bytes for smaller decimal values:

```python
In [9]: import pyarrow as pa

In [10]: import pyarrow.parquet as pq

In [11]: from decimal import Decimal

In [12]: import pandas as pd

In [13]: t = pa.Table.from_pandas(pd.DataFrame({'a': [Decimal('123.4')]}))

In [14]: pq.write_table(t, 'foobar.parquet')
```

```sh
$ parquet-dump-schema  foobar.parquet # comes from parquet-cpp
message schema {
  optional fixed_len_byte_array(2) a (DECIMAL(4,1));
  optional int64 __index_level_0__;
}
```

**Comment by cpcloud** [comment]
@c-nichols I know what the problem is, I'll comment on your PR.

**Comment by c-nichols** [comment]
Thanks again @cpcloud !

**Comment by naveenarumugam** [comment]
Thanks @c-nichols  @cpcloud  I'm going to test it with new v1.0.

**Comment by andrewgross** [comment]
Weird question for you @c-nichols, does Redshift CSV always export Numeric fields with the correct precision/scale for the field?  I was implementing this in my JSON converter and had a lot of issues coaxing JSON floats to the correct scale for decimal.
