### ISSUE TITLE
Add unicode support on Python 2

### ISSUE THREAD

**Issue by naveenarumugam** [hellonarrativ/spectrify#16]
* Spectrify version: 0.4.0
* Python version: 2.7
* Operating System: CentOS

### Description

  File "/usr/lib/python2.7/site-packages/spectrify/convert.py", line 70, in convert_redshift_manifest_to_parquet
    convert_parallel(manifest, sa_table, out_dir, workers, compression_type)
  File "/usr/lib/python2.7/site-packages/spectrify/convert.py", line 84, in convert_parallel
    pool.map(_parallel_wrapper, convert_args, chunksize=1)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-17: ordinal not in range(128)

### What I Did

```
Convert CSV to Parquet file
```

**Comment by c-nichols** [comment]
Hi @naveenarumugam, unicode support is limited to Python 3 right now.  This is because the python csv module in python 2 does not support unicode.  There are third-party solutions for this (e.g. unicodecsv), but I have not integrated one as yet.

**Comment by naveenarumugam** [comment]
Thanks @c-nichols; will try it out...do you've any thoughts on it?

**Comment by c-nichols** [comment]
I have limited experience with unicodecsv, but performance would be my main concern.  unicodecsv is written in Python, whereas the Python csv module is written largely in C.  As always, benchmarks would be required to say if it's significant, and I could see it being somewhat data-dependent as well.

**Comment by naveenarumugam** [comment]
@c-nichols  Agree.    
About pandas, yes, there are some cases needs to be handled and did not want to re-invent chunk writing again ... where you've handled it already.  Now, the biggest blocker is only about data type mappings...  hopefully, we'll have some updates.  For Unicode, I'll take it case by case for now.

**Comment by nirmo-lightricks** [comment]
Hi guys,

Note that now Spectrify has unicode support (with __Python2__). all you need to do is to export the environment variable: `SPECTRIFY_USE_UNICODE_CSV=1` then, just execute spectrify as before.

**Comment by c-nichols** [comment]
Thanks @nirmo-lightricks!!
