### ISSUE TITLE
ValueError: Type <class 'sqlalchemy.sql.sqltypes.REAL'> not currently supported by Spectrify. Open an issue?

### ISSUE THREAD

**Issue by dorianbg** [hellonarrativ/spectrify#37]
* Spectrify version: latest 
* Python version: 3.6
* Operating System: Mac OS

### Description

Copying a table with real column - actually a float4 column

### What I Did

```
spectrify transform
```

I think it is related to this piece of code 
https://github.com/hellonarrativ/spectrify/blob/master/spectrify/utils/schema.py

**Comment by andrewgross** [comment]
I wonder if this is related to Redshift seeing `FLOAT` as `FLOAT8`, and everything else seeing `FLOAT` as `FLOAT4`, which correlates with `REAL`.

**Comment by dorianbg** [comment]
Yes it might be, the only numeric datatypes I have are **int4** and **float4**

**Comment by dorianbg** [comment]
Seems like altering float4 columns to float8 would be the quickest fix?

**Comment by andrewgross** [comment]
Correct.

**Comment by c-nichols** [comment]
Open to PRs for this, if anyone is up for it!

**Comment by eliran-lightricks** [comment]
Opened #41 !

**Comment by c-nichols** [comment]
Thanks @eliran-lightricks!!
