### ISSUE TITLE
Clarifying comment

### ISSUE THREAD

**Issue by wesm** [hellonarrativ/spectrify#4]
You wrote in the code:

```
# pyarrow only supports 64-bit ints right now, so turn everything into int64's
# This is obviously inefficient across a number of dimensions...
# TODO: PR to pyarrow to support narrower ints
```

Could you clarify what you mean?

**Comment by c-nichols** [comment]
Wes, I was unable to write a table containing int32, int16, etc. last time I tried was quite some versions ago, perhaps support has changed?

I'll try to replicate in a smaller example this weekend.

**Comment by wesm** [comment]
It's possible it's been fixed already, but wanted to see on what code path that was happening so I can have a look myself

**Comment by c-nichols** [comment]
Hi Wes, see below for code path.  Looks like it has indeed been fixed, with the addition of the type converesion/casts. I added a couple possible improvements for pure-python implementations like spectrify's.

```
import pyarrow as pa
from pyarrow import parquet as pq
ints = [1,2,3,4]

# Succeeds
col64 = pa.array(ints, pa.int64())
col = col64.cast(pa.int16())

# Would be nice (bug?)
#col = pa.array(ints, pa.int16())
# >>> ArrowNotImplementedError: No type converter implemented for int16

# Succeeds
table = pa.Table.from_arrays([col], ['int16'])
writer = pq.ParquetWriter('test.parq', table.schema)
writer.write_table(table)
writer.close()

# Would be nice
#with pq.ParquetWriter('test.parq', table.schema) as writer:
#    writer.write_table(table)
# >>> AttributeError: __exit__

table1 = pq.read_table('test.parq')
table1.to_pydict()
# >>> OrderedDict([('int16', [1, 2, 3, 4])])
```

**Comment by wesm** [comment]
This works in master now:

```python
In [1]: import pyarrow as pa

In [2]: paste
ints = [1,2,3,4]

In [3]: pa.array(ints, type='int16')
Out[3]: 
<pyarrow.lib.Int16Array object at 0x7f80e284f1d8>
[
  1,
  2,
  3,
  4
]
```

**Comment by wesm** [comment]
This will land in pyarrow 0.8.0, but you can also try the nightlies with `conda install pyarrow -c twosigma`

**Comment by c-nichols** [comment]
Awesome! Thanks for taking a look, Wes.
