### ISSUE TITLE
issue with cli command

### ISSUE THREAD

**Issue by bapi24** [hellonarrativ/spectrify#40]
* Spectrify version: recent stable version
* Python version: python 3.6.5
* Operating System: macos

### Description
Trying to get started with spectrify with command line tool

trying to perform the following:

Unload the table to s3 bucket
Properly encode the data into Parquet files in s3 bucket
Create a table of the same name in the spectrum schema in my Redshift cluster

### What I Did
I am trying to use the command-line tool to get started:
```bash
spectrify –host=example-url.redshift.aws.com –user=myuser –db=mydb transform my_table 's3://example-bucket/my_table'
``
![image](https://user-images.githubusercontent.com/11890901/45907677-ba74aa80-bdad-11e8-95a8-19bafff9eaf2.png)

**Comment by bapi24** [comment]
![pasted_image_9_21_18__2_45_pm](https://user-images.githubusercontent.com/11890901/45907744-058ebd80-bdae-11e8-8377-600231ed14d6.png)

**Comment by bapi24** [comment]
![spectrify-git-issue](https://user-images.githubusercontent.com/11890901/45911129-72ad4d80-bdc4-11e8-84b5-25d3dab80942.png)

**Comment by bapi24** [comment]
![spec 2](https://user-images.githubusercontent.com/11890901/45911219-683f8380-bdc5-11e8-9140-9dd2c8c03a16.png)

**Comment by c-nichols** [comment]
Hi @bapi24 it looks like you might be using a single dash or a smart dash before some of the parameters.  Make sure you use 2 dashes.  To construct the command, I suggest pasting one of the examples from the readme into Atom or another code editor, modifying that to use your host, etc., and then paste into terminal.
