### ISSUE TITLE
How can I simply import s3 folder (no Spectrum )

### ISSUE THREAD

**Issue by eromoe** [hellonarrativ/spectrify#44]
Hello,

The official copy command would got error, so I look into this project .

I see usage is
```
Usage: spectrify create_table [OPTIONS] S3_PATH SOURCE_TABLE DEST_TABLE
```

Here, what is `SOURCE_TABLE ` ??  I already have a s3 folder contains some parquet files .
And , redshift spectrum is not launched on China AWS .

I just want to import data from s3 to redshift .

**Comment by c-nichols** [comment]
Hi @eromoe this article may help — https://aws.amazon.com/about-aws/whats-new/2018/06/amazon-redshift-can-now-copy-from-parquet-and-orc-file-formats/

I do not think you need Spectrify to accomplish your goals - if you have any other questions the aws forums are also super helpful.
