### ISSUE TITLE
Adding REGION parameter to UNLOAD

### ISSUE THREAD

**Issue by xanderayes** [hellonarrativ/spectrify#50]
The UNLOAD query should have the option to receive the REGION parameter. 
When I don't specify the REGION, I get from S3 the error "S3ServiceException:The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.,Status 301,Error PermanentRedirect".

**Comment by c-nichols** [comment]
If I'm reading the docs correctly, this is a problem when your Redshift cluster is in a different region than the S3 bucket you're saving to.  This would be a great enhancement, thanks for getting the ball rolling in #49.

**Comment by mparker3** [comment]
This issue should be resolved with the release of [v3.0.0](https://pypi.org/project/spectrify/3.0.0/). Big thanks again to @acharp!
