### ISSUE TITLE
TEXT fields not supported

### ISSUE THREAD

**Issue by anomitra** [hellonarrativ/spectrify#51]
* Spectrify version: 2.0.0
* Python version: 3.7
* Operating System: Ubuntu 16.04 on Docker

### Description

It appears that `TEXT` fields are not supported (yet). I ran into this while converting a table which has some free text fields.

### What I Did

I ran the `convert` command. The output follows.

``ValueError: Type <class 'sqlalchemy.sql.sqltypes.TEXT'> not currently supported by Spectrify.``

Is there any particular reason why this was never supported, and can it be taken up as an enhancement? I might take a stab at it, if required.

**Comment by c-nichols** [comment]
There is no particular reason, it would be greatly appreciated as an enhancement!  #41 might be a good PR for inspiration.

**Comment by anomitra** [comment]
As per the [Redshift documentation](https://docs.aws.amazon.com/redshift/latest/dg/r_Character_types.html#r_Character_types-text-and-bpchar-types), a `TEXT` field is basically just `VARCHAR(256)`. Also, I converted all my `TEXT` fields to `VARCHAR` fields and everything worked fine.

It seems like adding a mapping for `TEXT` in the [data type mappings](https://github.com/hellonarrativ/spectrify/blob/master/spectrify/utils/parquet.py#L24) should suffice, along with a few regression tests. I'll try and get around to it during the weekend if I can!

**Comment by c-nichols** [comment]
@anomitra thank you for this!
