### ISSUE TITLE
Parquet conversion

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [hellonarrativ/spectrify#56]
Hey, this tool is amazing and simplified data engineer's life. 

Im trying to understand the principles of this tool.

It's converting the CSV to Parquet, just curious how it's doing this process without any Hadoop clusters?

**Comment by c-nichols** [comment]
Hi Bhuvi,

Spectrify uses the Apache Arrow project to write Parquet files.  Behind the scenes, Arrow uses the Apache-managed C++ parquet writer, parquet-cpp.

More info here: https://arrow.apache.org/docs/python/parquet.html
