### ISSUE TITLE
create_table does not append "/spectrum" at the end of the s3 path used for the location of the external table

### ISSUE THREAD

**Issue by acharp** [hellonarrativ/spectrify#58]
* Spectrify version:2.0.0
* Python version:2.7.11 ; 3.5.7 ; 3.6.7
* Operating System: OS X Mojave 10.14.6

### Description

When creating the external table with the `create_table` cli command, `/spectrum` is not appended at the end of the s3 path used for the `location` of the external table. Therefore, when we then try to query the table, it fails because spectrum ends up looking in the `/csv` folder instead of the `/spectrum` one and find files with an unexpected format: csv instead of parquet.

I have noticed that the `transform` command does not have this issue : it correctly append `/spectrum` to the s3 path as it should.

I investigated a bit and this very likely comes from the fact that, for `create_table`, the `s3_config` is instantiated directly from `SimpleS3Config()` [here](https://github.com/hellonarrativ/spectrify/blob/master/spectrify/main.py#L76) whereas for `transform`, the `s3_config` is created through `SimpleS3Config.from_base_path` [here](https://github.com/hellonarrativ/spectrify/blob/master/spectrify/main.py#L38) which takes care of appending `/spectrum` to `the spectrum_dir` field.
\
\
Let me know if all that makes sense and if I'm on the right track. I can work on it when I'll get your green light.
Cheers!

**Comment by c-nichols** [comment]
Hi @acharp!  Sorry for the delay here.  You are indeed on the right track -- thanks for the report, if you're still game to work on this by all means go ahead!

**Comment by acharp** [comment]
Hello @c-nichols, no worries about the delay. I know how hectic it can get :) 
And yes I should have some time to work on this in the coming days, stay tuned for the PR.

**Comment by acharp** [comment]
It was such a short one I ended up doing it now : https://github.com/hellonarrativ/spectrify/pull/59

**Comment by mparker3** [comment]
This issue should be resolved with the release of [v3.0.0](https://pypi.org/project/spectrify/3.0.0/) Big thanks to @acharp!
