### ISSUE TITLE
Partitioned Table Support

### ISSUE THREAD

**Issue by andrewgross** [hellonarrativ/spectrify#7]
Hey,

Awesome work on this.  I did some similar stuff internally using Spark as the conversion engine instead of PyArrow.  Did you have plans to add partitioning support?  It might be a bit tricky due to data size and needing to inspect/sort the CSV data in Python.

I did some similar work on a JSON -> Parquet converter that we use with Spectrum

https://github.com/andrewgross/json2parquet

And added support for partitioning, but it relied on inspecting DateTime objects in Python, which was not particularly CPU or memory efficient.

**Comment by c-nichols** [comment]
Cool stuff!  Lots of similarities there.

Would be awesome to have partition support.  One option is to do the filtering on the redshift side in the `UNLOAD` query. Perhaps Spectrify could allow the user to specify a SqlAlchemy filter query.  This would allow the user to export an arbitrary slice of data -- for instance, the most recent complete month.

After that, the remaining pieces are 1) run parquet conversion for each discrete export, and 2) add to an existing table.  Spectrify should probably have some options to make this easier (specify destination folder, run `add partition` query).

What do you think?

**Comment by andrewgross** [comment]
`UNLOAD` is not a bad idea, but might run in to perf issues, even if the table is sorted on the partitioning key.   In my testing unloading a ~5bn row table by day took about 4 days vs unloading the entire table at once in about 4 hours.

Unfortunately, this then pushes the partitioning to the local machine, and it might not be feasible to do that in python for do to that all in memory.  

I think it is reasonable to do a best effort support at unloading each partition from Redshift and pushing that to S3.  Creating the table with partition support and adding the partition to the metastore would be awesome.  It might require querying Redshift for the existence of a table to ensure it exists before adding a partition.

Overall, I like the idea of adding it, even if it won't scale perfectly.

**Comment by woodlee** [comment]
In theory, if the Redshift distkey and sortkey are both set to the value you want to partition by, and the table is fully sorted (i.e. `VACUUM`ed to 100%), full unloads from the table would contain all records for each value of the key in a contiguous block. So you could just detect when it changes and do the output partition switch then.

Basically, it's just asking Redshift to do the redistribution work for you, instead of Spark or whatever. 

Haven't tried this myself yet, so there might be pitfalls, but just an idea I had when working on something similar. It'd probably require making a copy of the table before unloading in most cases, which might not always be feasible.

**Comment by andrewgross** [comment]
Fair point, I did not have tables fully sorted on the dist/partition key when i did my testing.  Curious how fast it would be in that case.  Definitely agree with not using Python/Arrow/Spectrify to do the bulk sorting work.

**Comment by naveenarumugam** [comment]
@c-nichols  @andrewgross  for now, I modified the custom version (will try to do generic ... to be able to raise a PR) to enable (1) partitioned CSV unload and (2) partitioned convert. As it's one time operation, DDL did not change yet.   I did the changes to export.py and for conversion, I am passing a dummy table with new column order, which is working okay.   But, obviously, trying to fix on issues such as Unicode, and Numeric data type

**Comment by andrewgross** [comment]
PyArrow Parquet recently added support for `write_to_dataset` which allows a partition key.  I have not used it extensively or attempted to hook it in to an S3 uploader.

**Comment by naveenarumugam** [comment]
Thanks @andrewgross.  I had done something similar. But, this is awesome, will be helpful going forward.

**Comment by c-nichols** [comment]
It's now simpler to modify Spectrify to do what you want (after latest refactor).  If you can achieve acceptable performance with partitioned `UNLOAD`s, it's fairly simple to get partitioning behavior.  I'll try to work on some documentation or a blog post or something over the next week or so.

@andrewgross `write_to_dataset` is really interesting.  I'm not quite sure what the best way to integrate it would be.  The difficulty is that the memory requirement increases to `<num_partitions> * <row_group_size>` per worker from just `<row_group_size>`.  That's probably fine for a relatively small number of partitions, but not for hundreds or thousands.

The whole point of arrow is to help solve problems like this, but Spectrify is really only using arrow to dump to Parquet right now.  It would require a closer integration with the memory model/IPC features of arrow, which would take some time and frankly might be beyond the scope of this project. Unless someone wants to write a CSV/string parser for arrow... :)

**Comment by c-nichols** [comment]
Hey all,

I've added documentation about custom workflows here: https://spectrify.readthedocs.io/en/stable/usage.html

And added an example script demonstrating partitioning here: https://github.com/hellonarrativ/spectrify/blob/master/examples/weekly_partitions.py

It's not an "out of the box" solution, but given the varying workflows/use cases around partitioning, I thought a flexible implementation was best.

If you have any thoughts on improving or adding to this, don't hesitate to open a new issue or reopen this one if you feel it's appropriate
